api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(
    'ingredients',
    views.IngredientViewSet,
    basename='ingredients'
)
router.register(
    'subscriptions',
    views.SubscriptionViewSet,
    basename='subscriptions'
)
router.register('favorites', views.FavoriteViewSet, basename='favorites')
router.register('purchases', views.PurchaseViewSet, basename='purchases')

urlpatterns = [
    path('', include(router.urls)),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'service_pages.views.page_not_found'  # noqa
handler500 = 'service_pages.views.server_error'  # noqa
handler400 = 'service_pages.views.bad_request'  # noqa

urlpatterns = [
    path('master-chef/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('service/', include('service_pages.urls')),
    path('api/', include('api.urls')),
    path('', include('recipes.urls')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'subscriptions/',
        views.subscription_index,
        name='subscriptions'
    ),
    path('users/<str:username>/', views.profile, name='profile'),
    path('recipes/new/', views.recipe_new, name='recipe_new'),
    path('recipes/<int:recipe_id>/', views.recipe_view, name='recipe_view'),
    path(
        'recipes/<int:recipe_id>/edit/',
        views.recipe_edit,
        name='recipe_edit'
    ),
    path(
        'recipes/<int:recipe_id>/delete/',
        views.recipe_delete,
        name='recipe_delete'
    ),
    path(
        'recipes/favorite/',
        views.recipe_favor,
        name='recipe_favor'
    ),
    path('purchase/', views.purchase_cart, name='purchase'),
    path('save-purchase/', views.purchase_save, name='purchase_save'),
]

recipes/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.deletion import CASCADE

MESSAGE_MIN_TIME = 'Время приготовления должно быть не меньше 1 минуты.'
MESSAGE_MIN_QUANTITY = 'Количество ингредиента должно быть не меньше 1'

User = get_user_model()


class Tag(models.Model):
    name = models.CharField('имя тэга', max_length=255)
    value = models.CharField('слаг тэга', max_length=50)
    color = models.CharField('цвет тэга в шаблоне', max_length=30, null=True)

    class Meta:
        verbose_name = 'тэг'
        verbose_name_plural = 'тэги'

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    title = models.CharField('ингредиент', max_length=500)
    dimension = models.CharField('единица измерения', max_length=20)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['title', 'dimension'],
                name='unique_ingredient'
            ),
        ]
        ordering = ['title']
        verbose_name = 'ингредиент'
        verbose_name_plural = 'ингредиенты'

    def __str__(self):
        return f'{self.title}, {self.dimension}'


class RecipeQuerySet(models.QuerySet):
    # отдельная выборка через теги
    def get_by_tags(self, tag, user):
        return (
            self.filter(tag__value__in=tag).distinct().is_annotated(user=user)
            if tag
            else self.is_annotated(user=user)
        )

    # отдельная выборка для избранного
    def user_favor(self, user):
        favorite_recipes = list(
            user.favorites.all().values_list('recipe_id', flat=True)
        )
        return self.filter(id__in=favorite_recipes)

    # отдельная выборка для заказов
    def user_purchase(self, user):
        purchase_recipes = list(
            user.purchases.all().values_list('recipe_id', flat=True)
        )
        return self.filter(id__in=purchase_recipes)

    def is_annotated(self, user):
        if user.is_authenticated:
            in_purchases = Purchase.objects.filter(
                recipe=models.OuterRef('id'),
                user=user
            )
            in_favor = Favorite.objects.filter(
                recipe=models.OuterRef('id'),
                user=user
            )
            in_subs = Subscription.objects.filter(
                author=models.OuterRef('author'),
                user=user
            )
            # возврат queryset'a
            return self.annotate(
                favorite=models.Exists(in_favor),  # рецепт в избранном
                purchased=models.Exists(in_purchases),  # вхождение в заказ
                subs=models.Exists(in_subs)  # вхождение в подписку
            )
        return self


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=CASCADE,
        verbose_name='автор',
        related_name='recipes'
    )
    title = models.CharField('название рецепта', max_length=200)
    image = models.ImageField('изображение', upload_to='recipes/',)
    description = models.TextField(
        'описание рецепта',
        blank=False,
        null=False
    )
    ingredients = models.ManyToManyField(
        Ingredient,
        through='VolumeIngredient',
        through_fields=('recipe', 'ingredient')
    )
    tag = models.ManyToManyField(Tag, verbose_name='тэг')
    time = models.PositiveSmallIntegerField(
        'время приготовления, мин.',
        validators=[MinValueValidator(1, message=MESSAGE_MIN_TIME)]
    )
    pub_date = models.DateTimeField(
        'дата публикации',
        auto_now_add=True,
        db_index=True
    )
    objects = RecipeQuerySet.as_manager()

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'рецепт'
        verbose_name_plural = 'рецепты'

    def __str__(self):
        return self.title


class VolumeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='volume_ingredient')
    ingredient = models.ForeignKey(
        Ingredient,
        verbose_name='ингредиент',
        on_delete=CASCADE,
        related_name='volume_ingredient'
    )
    quantity = models.PositiveIntegerField(
        'количество',
        validators=[MinValueValidator(1, message=MESSAGE_MIN_QUANTITY)]
    )

    class Meta:
        verbose_name = 'ингредиент в рецепте'
        verbose_name_plural = 'ингредиенты в рецепте'

    def __str__(self):
        return (f'{self.ingredient.title} - {self.quantity} '
                f'{self.ingredient.dimension}')


class Subscription(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='автор рецепта',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_subscription'
            ),
            # запрет подписки на уровне БД
            models.CheckConstraint(
                name='self_subscription_denied',
                check=~models.Q(user=models.F('author')),
            ),
        ]
        verbose_name = 'подписка'
        verbose_name_plural = 'подписки'

    def clean(self):
        if self.author == self.user:
            raise ValidationError(
                'Пользователь не может подписываться сам на себя'
            )


class Favorite(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='favorites',
        verbose_name='пользователь'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='favorites',
        verbose_name='рецепт'
    )

    class Meta:
        verbose_name = 'избранное'
        verbose_name_plural = 'избранное'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'recipe'],
                name='unique_favorite'
            ),
        ]


class Purchase(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='purchases',
        verbose_name='пользователь'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='purchases',
        verbose_name='рецепт'
    )

    class Meta:
        verbose_name = 'покупка'
        verbose_name_plural = 'покупки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'recipe'],
                name='unique_purchase'
            ),
        ]

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import RecipeForm
from .models import Recipe, Subscription, User
from .utils import check_paginator, split_on_page


# список рецептов для главной страницы
@cache_page(20, key_prefix='index_page')
def index(request):
    active_tags = request.META['active_tags']
    recipes = Recipe.objects.get_by_tags(tag=active_tags, user=request.user)
    selection = split_on_page(request, recipes)
    context = {'filters': request.META['url_tail_tags'], **selection}
    template = 'recipes/index.html'
    return check_paginator(request, selection, template, context)


# страница автора рецептов
def profile(request, username):
    active_tags = request.META['active_tags']
    user = get_object_or_404(User, username=username)
    recipes = Recipe.objects.filter(
        author=user
    ).select_related('author').get_by_tags(tag=active_tags, user=request.user)
    selection = split_on_page(request, recipes)
    context = {
        'filters': request.META['url_tail_tags'],
        'author': user,
        **selection
    }
    template = 'recipes/authorRecipe.html'
    return check_paginator(request, selection, template, context)


# список подписок пользователя
@login_required
def subscription_index(request):
    subscriptions = Subscription.objects.filter(user=request.user)
    selection = split_on_page(request, subscriptions)
    context = {'subscriptions': subscriptions, ** selection}
    template = 'recipes/myFollow.html'
    return check_paginator(request, selection, template, context)


# любимые рецепты пользователя
@login_required
def recipe_favor(request):
    active_tags = request.META['active_tags']
    favorites = Recipe.objects.user_favor(
        user=request.user
    ).get_by_tags(tag=active_tags, user=request.user)
    selection = split_on_page(request, favorites)
    context = {'filters': request.META['url_tail_tags'], **selection}
    template = 'recipes/favorite.html'
    return check_paginator(request, selection, template, context)


# страница рецепта
def recipe_view(request, recipe_id):
    recipe = get_object_or_404(
        Recipe.objects.is_annotated(user=request.user),
        id=recipe_id
    )
    return render(
        request,
        'recipes/single_recipe.html',
        {'recipe': recipe},
    )


# новый рецепт
@login_required
def recipe_new(request):
    form = RecipeForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        form.instance.author = request.user
        form.save()
        return redirect('recipe_view', form.instance.id)
    return render(request, 'recipes/formRecipe.html', {'form': form})


# редактирование рецепта
@login_required
def recipe_edit(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if recipe.author != request.user:
        return redirect('recipe_view', recipe_id)
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
        instance=recipe  # использую в форме через kwargs
    )
    context = {'form': form, 'recipe': recipe}
    if form.is_valid():
        form.save()
        return redirect('recipe_view', recipe.id)
    return render(request, 'recipes/formRecipe.html', context)


# удаление рецепта
@login_required
def recipe_delete(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.user == recipe.author:
        recipe.delete()
    return redirect('index')


# список покупок
@login_required
def purchase_cart(request):
    purchase = Recipe.objects.user_purchase(user=request.user)
    return render(
        request,
        'recipes/shopList.html',
        {'purchase': purchase}
    )


@login_required
def purchase_save(request):
    lenght = 0
    title = 'recipe__ingredients__title'
    dimension = 'recipe__ingredients__dimension'
    quantity = 'recipe__volume_ingredient__quantity'
    ingredients = request.user.purchases.select_related('recipe').order_by(
        title).values(title, dimension).annotate(amount=Sum(quantity)).all()
    if not ingredients:
        return render(request, '/misc/400.html', status=400)
    text = 'Веб-приложение foody-doody.ru\n\nСписок покупок:\n\n'
    # определяю самое длинное название ингредиента
    for i in ingredients:
        if len(i[title]) > lenght:
            lenght = len(i[title])
    # генерирую текст списка ингредиентов
    for number, ingredient in enumerate(ingredients, start=1):
        amount = ingredient['amount']
        # для удобства чтения списка покупок делаю динамические отступы
        num = f'{number})'.rjust(3, ' ')
        ing_title = ingredient[title].capitalize().ljust(lenght + 3, '.')
        text = '{}{}'.format(
            text,
            f'{num}{ing_title}{amount}, {ingredient[dimension]}\n'
        )
    footer = "\nIt's Foody-Doody time!"
    text = '{}{}'.format(text, footer)
    response = HttpResponse(text, content_type='text/plain')
    filename = 'purchases.txt'
    response['Content-Disposition'] = f'attachment; filename={filename}'
    return response

recipes/templates/recipes/authorRecipe.html
{% extends "foodgram/base.html" %}
{% load static %}
{% load recipes_filters %}
{% csrf_token %}

{% block title %}Pецепты автора {% firstof author.get_full_name author.username %}{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/pages/index.css' %}">
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">{% firstof author.get_full_name author.username %}</h1>
        {% include 'recipes/extend/tags.html' %}
    </div>
    {% if user.is_authenticated %}
        {% include 'recipes/extend/buttons/subs_button.html' with tagging='p' style='padding: 0 0 2em 0;' check=page.0.subs %}
    {% endif %}

<!-- Отображение карточки рецепта -->
    <div class="card-list">
        {% for recipe in page %}
            {% include "recipes/extend/recipe_item.html" %}
        {% endfor %}
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/authorRecipe.js' %}"></script>
{% endblock %}

recipes/templates/recipes/favorite.html
{% extends "foodgram/base.html" %}
{% load static %}
{% load recipes_filters %}

{% block title %}Избранное{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/pages/index.css'%}">
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">Избранное</h1>
        {% include "recipes/extend/tags.html" %}
    </div>
    <div class="card-list">
        {% for recipe in page %}
            {% include 'recipes/extend/recipe_item.html' with author=recipe.author%}
        {% endfor %}
    </div>
    {% if not page %}
        <a class="card__text" style="font-size: 20px; color: black;">У Вас пока нет любимых рецептов, или рецептов с данным тегом.</a>
        <br>
        <br>
        <a class="card__text" style="font-size: 20px;" href="{% url 'index' %}">На главной странице</a>
        <a class="card__text" style="font-size: 20px;"> Вы обязательно найдёте что-нибудь интересное</a>
    {% endif %}
{% endblock %}

{% block script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/favorite.js' %}"></script>
{% endblock %}

recipes/templates/recipes/formRecipe.html
{% extends "foodgram/base.html" %} 
{% load static %} 
{% load recipes_filters %} 
 
{% block title %}{{ recipe|yesno:"Редактирование рецепта,Создание рецепта" }}{% endblock %} 
 
{% block style %} 
    <link rel="stylesheet" href="{% static 'css/pages/form.css'%}"> 
{% endblock %} 
 
 
{% block content %} 
    <main class="main container" autocomplete="off">
        <div class="main__header"> 
            <h1 class="main__title">{{ recipe|yesno:"Редактирование рецепта,Создание рецепта" }}</h1> 
        </div> 
        <div class="form-container"> 
            <form class="form" method="post" enctype="multipart/form-data"> 
                {% csrf_token %} 
 
                {% with form.title as field %}
                    <div class="form__group" aria-required="{% if field.field.required %}true{% else %}false{% endif %}">
                        <label for="{{ field.id_for_label }}" class="form__label">Название рецепта</label>
                        <div class="form__field-group">
                            {{ field|addclass:'form__input' }}
                        {% include 'recipes/extend/form_extend/error.html' with field=field %}
                        </div>
                    </div>
                {% endwith %}

                <div class="form__group" aria-required="{% if form.tag.field.required %}true{% else %}false{% endif %}">
                    <div class="form__field-group">
                        {% include "recipes/extend/form_extend/tags_for_form.html" %}
                        {% if form.tag.errors %}
                            <span class="form__error">Добавьте по крайней мере один тег</span>
                        {% endif %}
                    </div> 
                </div>

                {% include "recipes/extend/form_extend/ingredients.html" with field=form.ingredients_in_recipe%}

                <div class="form__group">
                    {% with form.time as field %}
                        <label for="{{ field.id_for_label }}" class="form__label">Время приготовления</label>
                        <div class="form__field-group form__field-group_time">
                            {{ field|addclass:'form__input' }}
                            <label for="id_time" class="form__label">мин.</label>
                            {% include 'recipes/extend/form_extend/error.html' %}
                        </div>
                    {% endwith %}
                </div>

                <div class="form__group">
                    {% with form.description as field %}
                        <label for="{{ field.id_for_label }}" class="form__label">Описание рецепта</label>
                        <div class="form__field-group">
                            {{ field|addclass:'form__textarea' }}
                            {% include 'recipes/extend/form_extend/error.html' %}
                        </div>
                    {% endwith %}
                </div>

                <div class="form__group">
                    <span class="form__label">Загрузить фото</span>
                    <div class="form__field-group">
                        {{ form.image }}
                        <span class="form__error">{{ form.image.errors }}</span>
                    </div>
                </div> 
 
                {% include "recipes/extend/buttons/save_button.html" %}

            </form> 
        </div> 
    </main> 
{% endblock %} 
 
{% block script %} 
    <script src="{% static 'js/config/config.js' %}"></script> 
    <script src="{% static 'js/components/Header.js' %}"></script> 
    <script src="{% static 'js/utils/debouncing.js' %}"></script> 
    <script src="{% static 'js/api/Api.js' %}"></script> 
    <script src="{% static 'js/formRecipe.js' %}"></script>
{% endblock %}

recipes/templates/recipes/index.html
{% extends "foodgram/base.html" %}

{% block title %}Pецепты{% endblock %}

{% load static %}
{% load recipes_filters %}
{% csrf_token %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/pages/index.css'%}">
{% endblock %}

{% block index %}
    <li class="nav__item nav__item_active">
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">Рецепты</h1>
        {% include "recipes/extend/tags.html" %}
    </div>

    <div class="card-list">
        {% for recipe in page %}
            {% include "recipes/extend/recipe_item.html" with author=recipe.author %}
        {% endfor %}
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    {% if user.is_authenticated %}
        <script src="{% static 'js/indexAuth.js' %}"></script>
    {% else %}
        <script src="{% static 'js/indexNotAuth.js' %}"></script>
    {% endif %}
{% endblock %}

recipes/templates/recipes/myFollow.html
{% extends "foodgram/base.html" %}
{% load static %}
{% csrf_token %}
{% load recipes_filters %}

{% block title %}Мои подписки{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/pages/myFollow.css' %}">
{% endblock %}

{% block content %}
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>
    <div class="card-list">
        {% for item in page %}
            {% include "recipes/extend/follow_item.html" with author=item.author %}
        {% endfor %}
    </div>
    {% if not page %}
        <a class="recipe__text" style="font-size: 20px; color: black;">У Вас пока нет любимых авторов</a>
        <br>
        <br>
        <a class="recipe__text" style="font-size: 20px;" href="{% url 'index' %}">На главной странице</a>
        <a class="recipe__text" style="font-size: 20px;"> Вы обязательно найдёте интересного автора</a>
    {% endif %}
{% endblock %}

{% block script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/MyFollow.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/myFollow.js' %}"></script>
{% endblock %}

recipes/templates/recipes/shopList.html
{% extends 'foodgram/base.html' %}

{% block title%} Список покупок {% endblock%}
   
{% load static %}
{% load recipes_filters %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/pages/shopList.css' %}">
{% endblock %}
    
{% block content %}
    <div class="main__header">
        <h1 class="main__title">Список покупок</h1>
    </div>
    <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for recipe in purchase %}
                {% csrf_token %}
                <li class="shopping-list__item" data-id="{{ recipe.id }}">
                    <a href="{% url 'recipe_view' recipe.id %}" style="text-decoration: none;">
                        <div class="recipe recipe_reverse">

                            {% include 'recipes/extend/image.html' with size="144x144" class="recipe__image recipe__image_big" small_pix=True %}

                            <h3 class="recipe__title">{{ recipe.title }}</h3>
                            {% include 'recipes/extend/icon_extend/icon_time.html' with class="recipe__text" time=recipe.time %}
                        </div>
                    </a>
                    <a class="shopping-list__button link">Удалить</a>
                </li>
            {% endfor %}
        </ul>
        {% if purchase %}
            <a class="shopping-list__button link" style="font-size: 20px;" href="{% url 'purchase_save' %}">
                <button class="button button_style_blue">Скачать список</button>
            </a>
        {% else %}
            <a class="shopping-list__button" style="font-size: 20px; color: black;">Ваш список рецептов пока пуст</a>
            <a class="shopping-list__button link" style="font-size: 20px;" href="{% url 'index' %}">Добавьте рецепты на главной странице</a>
        {% endif %}
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/components/ShopList.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/shopList.js' %}"></script>
{% endblock %}

recipes/templates/recipes/single_recipe.html
{% extends "foodgram/base.html" %}
{% load static %}

{% block title %}{{ recipe.title }}{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/pages/single.css'%}">
{% endblock %}

{% block content %}
    {% csrf_token %}
    <div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
    
    {% include 'recipes/extend/image.html' with size="480x480" class="card__image" %}

        <div class="single-card__info">
            <div class="single-card__header-info">
                <h1 class="single-card__title"> {{ recipe.title }} </h1>
                <div class="single-card__favorite">
                    {% if user.is_authenticated %}
                        {% include 'recipes/extend/buttons/favor_button.html' with check=recipe.favorite %}
                        <div class="single-card__favorite-tooltip tooltip">{{ recipe.favorite|yesno:'Убрать из избранного, Добавить в избранное'}}</div>
                    {% endif %}
                </div>
            </div>
            {% include 'recipes/extend/icon_extend/icon_tags.html' with class_1="single-card__items" class_2="single-card__item" tags=recipe.tag.all %}
            <div class="single-card__items single-card__items_column">
                {% include 'recipes/extend/icon_extend/icon_time.html' with class="single-card__text" time=recipe.time %}
                <ul class="single-card__items">
                    <li class="single-card__item">
                        {% include 'recipes/extend/icon_extend/icon_user.html' with class="single-card__text" author=recipe.author %}
                    </li>
                    {% if user == recipe.author %}
                        <li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'recipe_edit' recipe.id %}" class="single-card__text">Редактировать рецепт</a></li>
                    {% endif %}
                </ul>
            </div>
            <ul class="single-card__items">
                {% if user.is_authenticated %}
                    <li class="single-card__item">
                        {% include 'recipes/extend/buttons/purchase_button.html' with check=recipe.purchased single_recipe=True%}
                    </li> 
                    {% include 'recipes/extend/buttons/subs_button.html' with author=recipe.author tagging='li' style='height: 48px;' check=recipe.subs %}
                {% endif %}
            </ul>
            <div class="single-card__section">
                <h3 class="single-card__section-title">Ингредиенты:</h3>
                <div class="single-card__items single-card__items_column">
                    {% for ingredient in recipe.volume_ingredient.all %}
                        <p class=" single-card__section-item">{{ ingredient }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="single-card__section">
                <h3 class="single-card__section-title">Описание:</h3>
                <p class=" single-card__section-text">{{ recipe.description|linebreaksbr }}</p>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/SingleCard.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/singlePage.js' %}"></script>
{% endblock %}