api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(
    'ingredients',
    views.IngredientViewSet,
    basename='ingredients'
)
router.register(
    'subscriptions',
    views.SubscriptionViewSet,
    basename='subscriptions'
)
router.register('favorites', views.FavoriteViewSet, basename='favorites')
router.register('purchases', views.PurchaseViewSet, basename='purchases')

urlpatterns = [
    path('', include(router.urls)),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'service_pages.views.page_not_found'  # noqa
handler500 = 'service_pages.views.server_error'  # noqa
handler400 = 'service_pages.views.bad_request'  # noqa

urlpatterns = [
    path('master-chef/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('service/', include('service_pages.urls')),
    path('api/', include('api.urls')),
    path('', include('recipes.urls')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

service_pages/urls.py
from django.urls import path

from . import views

app_name = 'service'

urlpatterns = [
    path('author/', views.AuthorView.as_view(), name='author'),
    path('tech/', views.TechView.as_view(), name='tech'),
]

templates/foodgram/base_ext/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'index' %}" class="footer__brand link">
            FoodyDoody © {% now "Y" %}, все права защищены.
        </a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'service:author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'service:tech' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/foodgram/base_ext/nav.html
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item{% if mark == 'index' %} nav__item_active{% endif %}">
                    <a href="{% url 'index' %}" class="nav__link link">Рецепты</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav__item{% if mark == 'subscriptions' %} nav__item_active{% endif %}">
                        <a href="{% url 'subscriptions' %}" class="nav__link link">Мои подписки</a>
                    </li>
                    <li class="nav__item{% if mark == 'recipe_new' %} nav__item_active{% endif %}">
                        <a href="{% url 'recipe_new' %}" class="nav__link link">Создать рецепт</a>
                    </li>
                    <li class="nav__item{% if mark == 'recipe_favor' %} nav__item_active{% endif %}">
                        <a href="{% url 'recipe_favor' %}" class="nav__link link">Избранное</a>
                    </li>
                    <li class="nav__item{% if mark == 'purchase' %} nav__item_active{% endif %}">
                        <a href="{% url 'purchase' %}" class="nav__link link">Список покупок</a>
                        <span class="badge badge_style_blue nav__badge" id="counter">{% if tally %}{{ tally }}{% endif %}</span>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav__items list">
                {% if user.is_authenticated %}
                    <li class="nav__item{% if mark == 'profile' %} nav__item_active{% endif %}">
                        <a href="{% url 'profile' user.username %}" class="nav__link link">{{ user.username }}</a>
                    </li>
                    <li class="nav__item{% if mark == 'password_change' %} nav__item_active{% endif %}">
                        <a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'logout' %}" class="nav__link link">Выход</a>
                    </li>
                {% else %}
                    <li class="nav__item">
                        <a href="{% url 'login' %}" class="nav__link link">Войти</a>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'signup' %}" style='padding-top: 16px' class="button button_style_blue">Создать аккаунт</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

templates/foodgram/base_ext/paginator.html
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if page.has_previous %}
            <li class="pagination__item"><a class="pagination__link link" href="?page={{ page.previous_page_number }}{{ filters }}"><span class="icon-left"></span></a></li>
        {% endif %}
        {% for i in page.paginator.page_range %}
            {% if page.number == i %}
                <li class="pagination__item pagination__item_active"><a class="pagination__link link">{{ i }}</a></li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ i }}{{ filters }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page.has_next %}
            <li class="pagination__item"><a class="pagination__link link" href="?page={{ page.next_page_number }}{{ filters }}"><span class="icon-right"></span></a></li> 
        {% endif %} 
    </ul>
</nav>